config/routes.rb
NewsApp::Application.routes.draw do
  devise_for :users
  resources :links
  resources :comments
  resources :votes

  root to: 'links#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :link_id, :message, :user_id, :parent_id, :parent_link_id
  belongs_to :link
  has_ancestry

  validates :message, length: {minimum: 2}, presence: true

  default_scope order: 'comments.created_at ASC'


end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :comment, :title, :url, :user_id

  validates_format_of :url, :with => URI::regexp(%w(http https))
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true
  
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role
  # attr_accessible :title, :body


  # before_save {|user| user.name = name.downcase }
  before_save {|user| user.email = email.downcase }

  validates :name, presence: true, uniqueness: true, length: {minimum: 3}
  validates :email, uniqueness: true
  has_many :links

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :link_id, :up, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!

	def new

		@parent_link_id = (params[:parent_link_id])
		@parent = Comment.find(params[:parent_id])
		@comment = Comment.new(parent_id: params[:parent_id])
	end

	def create
		@comment = Comment.create(params[:comment])
		redirect_to link_path(@comment.link_id)
	end






end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	
	before_filter :authenticate_user!, except: [:index, :show]
	
	def new
		@link = Link.new
	end

	def create
		@link = Link.new(params[:link], user_id: :current_user)
		if @link.save
			flash[:success] = "Link was successfully created"
			redirect_to root_path
		else
			render :new
		end
	end


	def show
		@link = Link.find(params[:id])
		@comment = Comment.new
	end


	def edit
		@link = Link.find(params[:id])
	end


	def index
		@links = Link.order('created_at DESC').paginate(:page => params[:page], :per_page => 20)

		if params[:page].to_i == 0
			@offset = (@links.per_page) * (params[:page].to_i)
		else
			@offset = (@links.per_page) * (params[:page].to_i - 1)
		end

		if @links.empty?
			flash[:error] = "Threre are no links to view, create new link to proceed"
		end
	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		@vote = Vote.create(params[:vote])
		redirect_to link_path(@vote.link_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
		comments.map do |comment, sub_comments|
			render(comment) + content_tag(:div, nested_comments(sub_comments), class: "nested_comments")
		end.join.html_safe
	end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<%= time_ago_in_words(comment.created_at).gsub(/^about /, "") %> ago by
<%= link_to User.find(comment.user_id).name, '#' %>

<p>
	<%= comment.message %>
</p>

<p>
	<%= link_to 'Reply', new_comment_path(parent_id: comment, parent_link_id: comment.link_id ) %>
</p>

app/views/comments/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
	<%= render 'shared/comment_error_messages' %>

	<%= f.text_area :message, rows: "4", placeholder: "Add comment" %>

	<% if @link.present? %>
	<%= f.hidden_field :link_id, :value => @link.id %>
	<% else %>
	<%= f.hidden_field :link_id, value: @parent_link_id %>
	<% end %>

	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.hidden_field :parent_id %>


	<div><%= f.submit "Submit", class: "button" %></div>
<% end %>

app/views/comments/_comment_list.html.erb
<div>
	<%= nested_comments @link.comments.arrange(order: :created_at) %>
</div>

app/views/comments/new.html.erb
<div class="six columns offset-by-two">
<h4 class="header">New Message</h4>

<%= render @parent %>

<%= render 'comments/comment_form' %>


</div>

app/views/layouts/_footer.html.erb
<div class="twelve columns offset-by-two footer">
<small>Designed by Wontae Yang</small>
</div>

app/views/layouts/_header.html.erb
<div class="nav-container">
	<div class="nav twelve columns offset-by-two">
		<div class="title-wrapper">
			<div class="logo pull-left"></div>
			<%= link_to 'ARCHIVED', root_path, class: "title pull-left" %>
		</div>
	</div>
	<div class="sub-nav twelve columns offset-by-two">
		<div class="menu-wrapper">
			<ul class="menu">

				<li><%= link_to 'Submit', new_link_path %></li>

				<% if user_signed_in? %>
				<li><%= link_to 'Settings', edit_user_registration_path %></li>
				<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li><%= link_to 'Signup', new_user_registration_path %></li>
				<li><%= link_to 'Login', new_user_session_path %></li>
				<% end %>

			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ARCHIVED/NEWS</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag "/favicon.ico" %>
	<!-- mobile specific meta tab -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=1">
</head>

<body>
	<div class="container">
		<%= render 'layouts/header' %>
			<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "flash") %>
			<% end %>
		<div class="custom-body">
			

			<%= yield %>

		</div>
	<%= render 'layouts/footer' %>
	</div>
</body>

</html>

app/views/links/index.html.erb
<div class="twelve columns offset-by-two">
	<table class="links-table">
		<% @links.each_with_index do |p, index| %>
		<tbody>

			<tr>
				<td class="links-numbering">
					<%= link_to votes_path(:vote => {:link_id => p.id, :up => true}), :method => :post do%>
						<!-- <i class="icon-plus"></i> -->
						<% end %>
					<%= index + @offset + 1 %>.
				</td>
				<td>
					<span class="links-title black-link">
						<%= link_to p.title.upcase, p.url %>
					</span>

					<span class="links-divider">
						| 
					</span>

					<span class="links-domain">
						<%= URI.parse(p.url).host.gsub(/\Awww\./, "")  %>
					</span>

				</td>

			</tr>
			<tr>
				<td>

				</td>
				<td class="links-user">
					<span class="">

						<%= time_ago_in_words(p.created_at).
          gsub(/^about /, "") %> ago by
						<%= link_to User.find(p.user_id).name, '#' %>
					</span> 

					<span class="">
						- <%= p.comments.all.count %> <%= link_to "comments", p %>
					</span> 
				</td>
			</tr>

			<% end %>
		</tbody>
	</table>


	<div class="paginate">
		<%= will_paginate @posts, page_links: false, next_label: "MORE", previous_label: ""  %>
	</div>

app/views/links/new.html.erb
<div class="six columns offset-by-two">
<h4 class="header">Submit a Link</h4>

<%= form_for(@link) do |f| %>
	<%= render 'shared/links_error_messages' %>
	
	<%= f.text_field :url, :autofocus => true, placeholder: "URL - Include http://" %>

	
	<%= f.text_field :title, placeholder: "Title" %>

	
	<%= f.text_area :comment, rows: "4", placeholder: "Comment" %>

	<div>
	<%= f.hidden_field :user_id, value: current_user.id %>
	</div>	


	<br />
	<div><%= f.submit "Submit", class: "button" %></div>
<% end %>


</div>

app/views/links/show.html.erb
<div class="twelve columns offset-by-two">

	<span class="links-title show-link black-link">
		<%= link_to @link.title.upcase, @link.url %>
	</span>

	<span class="links-divider show-link">
		| 
	</span>

	<span class="links-domain show-link">
		<%= link_to URI.parse(@link.url).host.gsub(/\Awww\./, "") , @link.url %>
	</span>
	<div class="">
		<%= time_ago_in_words(@link.created_at).
          gsub(/^about /, "") %> ago by
		<%= User.find(@link.user_id).name %>
	</div>

	<div class="links-comment">
		<%= @link.comment %>
	</div>


	<%= render 'comments/comment_form' %>
	

	<%= render 'comments/comment_list' %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/shared/_comment_error_messages.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @link.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links_error_messages.html.erb
<% if @link.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>